name: vessel_flutter
description: vessel for Flutter
version: 3.1.0
repository: https://github.com/AlexanderFarkas/vessel/tree/main/packages/vessel_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"
  

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  vessel: ^3.2.0
  meta: ^1.7.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1
  flutter_test:
    sdk: flutter
