name: vessel_flutter
description: vessel for Flutter
version: 1.0.0
repository: https://github.com/AlexanderFarkas/vessel/tree/master/packages/vessel_flutter

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=3.0.0"
  

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  vessel: ^0.9.1+1
  meta: ^1.7.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
