name: vessel
description: >-
  IoC-Container written in pure Dart with Flutter in mind.
  Provides compile-time checks, typed factories, scoping and much more.
version: 1.0.0
repository: https://github.com/AlexanderFarkas/vessel/tree/main/packages/vessel

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1

dependencies:
  meta: ^1.7.0

